<div class="col-sm-9">
    <div class="blog-post-area">
        <h2 class="title text-center">Our catalog</h2>
        <? foreach ($this->products as $product) : ?>
            <div class="single-blog-post">
                <h3><?=$product['product_name']?></h3>
                <div class="post-meta">
                    <ul>
                        <li><i class="fa fa-user"></i> Mac Doe</li>
                        <li><i class="fa fa-clock-o"></i> 1:33 pm</li>
                        <li><i class="fa fa-calendar"></i> DEC 5, 2013</li>
                    </ul>
                    <span>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star-half-o"></i>
								</span>
                </div>
                <a href="">
                    <img src="<?=$product['product_preview']?>" alt="">
                </a>
                <p><?=$product['product_description']?></p>
                <a class="btn btn-primary" href="">Read More</a>
            </div>
        <? endforeach; ?>
        <div class="pagination-area">
            <ul class="pagination">
                <li><a href="" class="active">1</a></li>
                <li><a href="">2</a></li>
                <li><a href="">3</a></li>
                <li><a href=""><i class="fa fa-angle-double-right"></i></a></li>
            </ul>
        </div>
    </div>
</div>